communities/urls.py
from django.conf import settings
from django.views.generic import RedirectView
from django.urls import path

from . import views


app_name = 'communities'
urlpatterns = [
    path('', views.FrontPage.as_view(), name='frontpage'),
    path('drawpile.net/ban/', views.BanPage.as_view(), name='ban'),
    path('drawpile.net/ccg/', views.GuideLinesPage.as_view(), name='ccg'),
    path('drawpile.net/ych/', views.YchPage.as_view(), name='ych'),
    path('drawpile.net/submit/', views.SubmitPage.as_view(), name='submit'),
    path('<slug>/', views.CommunityPage.as_view(), name='community'),
    path('<slug>/edit/',
        RedirectView.as_view(url='/readonly/', permanent=False)
        if settings.DRAWPILE_READONLY_SITE
        else views.EditPage.as_view(),
        name='edit'),
    path('<slug>/members/', views.Memberlist.as_view(), name='memberlist'),
    path('<slug>/review/',
        RedirectView.as_view(url='/readonly/', permanent=False)
        if settings.DRAWPILE_READONLY_SITE
        else views.review_community,
        name='review'),
    path('<slug>/i-am-old-enough/', views.community_confirm_age, name='confirm-age'),
    path('<slug>/server-help/', views.ServerHelpPage.as_view(), name='server-help'),
]

dpauth/urls.py
from django.urls import path, re_path
from . import views

app_name = "auth"
urlpatterns = [
    path("", views.AuthUsernamesView.as_view(), name="usernames"),
    re_path(r"^finish/(?P<name>.+)/$", views.AuthFinishView.as_view(), name="finish"),
    path("login/", views.AuthLoginView.as_view(), name="login"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
    path("ban-analyzer/", views.BanAnalyzerView.as_view(), name="ban-analyzer"),
    path(
        "monitor-manager/", views.MonitorManagerView.as_view(), name="monitor-manager"
    ),
    path(
        "monitor-manager/restart",
        views.MonitorManagerRestartView.as_view(),
        name="monitor-manager-restart",
    ),
]

drawpile/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf import settings

from templatepages.views import DocumentationDetailView, TemplatePageView


class DonationRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        try:
            lang = self.request.GET["lang"]
            if lang and lang.startswith("de_"):
                return self.url + "de/"
        except:
            pass
        return self.url


urlpatterns = [
    path('_admin/', admin.site.urls),
    path('api/', include('drawpile.api_urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('dpusers.urls')),
    path('auth/', include('dpauth.urls')),
    path('communities/', include('communities.urls')),
    path('invites/', include('invites.urls')),
    path('ban/', RedirectView.as_view(
        url='/communities/drawpile.net/ban/', permanent=True)),
    path('readonly/', TemplateView.as_view(template_name='readonly.html')
        if settings.DRAWPILE_READONLY_SITE
        else RedirectView.as_view(url='/', permanent=False)),
    path('discord/', RedirectView.as_view(url='https://discord.gg/VHRDh2fKnc', permanent=True)),
    path('fedi/', RedirectView.as_view(url='https://floss.social/@drawpile', permanent=True)),
    path('matrix/', RedirectView.as_view(url='https://matrix.to/#/#drawpile:matrix.org', permanent=True)),
    path('localhosthelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/common/hosting#builtin-server', permanent=True)),
    path('pubrules/', RedirectView.as_view(url='/communities/drawpile.net/ccg/', permanent=True)),
    path('sharedarraybufferhelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/tech/browser#sharedarraybuffer-issues', permanent=True)),
    path('lgm/', TemplateView.as_view(template_name='lgm.html')),
    path('namecheckbot/', TemplateView.as_view(template_name='namecheckbot.html')),
    path('donate/', DonationRedirectView.as_view(url="https://donate.drawpile.org/", permanent=True)),
    path('', TemplateView.as_view(template_name='pages/index.html')),
]

if hasattr(settings, "DRAWPILE_IMPRESSUM"):
    urlpatterns += path('impressum/', TemplateView.as_view(template_name='impressum.html')),

if hasattr(settings, "DRAWPILE_PRIVACY_POLICY"):
    urlpatterns += path('privacy/', TemplateView.as_view(template_name='privacy.html')),

if hasattr(settings, "DRAWPILE_TOS"):
    urlpatterns += path('tos/', TemplateView.as_view(template_name='tos.html')),

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    path('docs/<slug:slug>/', DocumentationDetailView.as_view(), name='documentation-detail'),
    re_path(r'^(?P<path>.*)/$', TemplatePageView.as_view()),
]

news/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.NewsListView.as_view(), name="list"),
    path('feed.atom', views.NewsFeed(), name="atom-feed"),
    path('release-2.3.0-beta.1/', RedirectView.as_view(url="/news/release-2.3.0-beta.2/", permanent=True)),
    path('<slug>/', views.NewsDetailView.as_view(), name='detail'),
]

communities/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from .utils import UploadNameFromContent

community_badge_upload_to = UploadNameFromContent('community/badges/', 'badge')


class Community(models.Model):
    STATUS_SUBMITTED = 'submitted'
    STATUS_RESUBMIT = 'resubmit'
    STATUS_ACCEPTED = 'accepted'
    STATUS_REJECTED = 'rejected'
    STATUSES = (
        (STATUS_SUBMITTED, 'Submitted, awaiting review'),
        (STATUS_RESUBMIT, 'Reviewed, awaiting resubmission'),
        (STATUS_ACCEPTED, 'Accepted'),
        (STATUS_REJECTED, 'Rejected (with prejudice)'),
    )

    GROUP_INVITE_ONLY = 'invite-only'
    GROUP_FREE_JOIN = 'free-join'
    GROUP_VERIFIED_JOIN = 'verified-join'
    GROUP_POLICY = (
        (GROUP_INVITE_ONLY, 'Invitation only'),
        (GROUP_FREE_JOIN, 'Anyone can join'),
        (GROUP_VERIFIED_JOIN,
            'Anyone can join, but must be verified by a moderator'),
    )

    HOST_EVERYONE = 'all-host'
    HOST_ACCOUNT = 'account-host'
    HOST_MEMBERS = 'member-host'
    HOST_LIMITED = 'limited-host'
    HOST_POLICY = (
        (HOST_EVERYONE, 'Everyone can host sessions'),
        (HOST_ACCOUNT, 'Anyone with an account can host'),
        (HOST_MEMBERS, 'Only group members can host'),
        (HOST_LIMITED, 'Only select users can host'),
    )

    MEMBERLIST_HIDDEN = 'hidden'
    MEMBERLIST_PRIVATE = 'private'
    MEMBERLIST_VISIBLE = 'visible'
    MEMBERLIST_VISIBILITY = (
        (MEMBERLIST_HIDDEN, 'Hidden'),
        (MEMBERLIST_PRIVATE, 'Visible to other members only'),
        (MEMBERLIST_VISIBLE, 'Visible to all logged in users'),
    )

    CONTENT_SFW = 'sfw'
    CONTENT_MIXED = 'mixed'
    CONTENT_ADULT = 'adult'
    CONTENT_RATINGS = (
        (CONTENT_SFW, "Safe-For-Work content only"),
        (CONTENT_MIXED, "Adult content is permitted but must be tagged"),
        (CONTENT_ADULT, "This is an adults only community"),
    )

    WEB_DISABLED = 'disabled'
    WEB_MANUAL = 'manual'
    WEB_PASSWORDED = 'passworded'
    WEB_OPEN = 'open'
    WEB_POLICY = (
        (WEB_DISABLED, 'Joining via web browser disabled'),
        (WEB_MANUAL, 'Joining via web browser only for manually-approved sessions'),
        (WEB_PASSWORDED, 'Joining via web browser only for passworded and manually-approved sessions'),
        (WEB_OPEN, 'Joining via web browser allowed without restrictions'),
    )

    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    title = models.CharField(
        max_length=100,
        help_text="The name of your community")
    slug = models.SlugField(
        unique=True,
        help_text="Short name (consisting only of letters a-z, numbers, "
                  "underscores or hyphens) for use in links. Note: this cannot " 
                  "be changed afterwards, except by site admins.")
    short_description = models.TextField()
    full_description = models.TextField()
    badge = models.ImageField(
        upload_to=community_badge_upload_to,
        # validators=[community_logo_validator]
        )

    rules = models.TextField()
    group_policy = models.CharField(
        verbose_name="Group membership",
        max_length=32,
        choices=GROUP_POLICY,
        default=GROUP_INVITE_ONLY)
    memberlist_visibility = models.CharField(
        verbose_name="Member list",
        max_length=32,
        choices=MEMBERLIST_VISIBILITY,
        default=MEMBERLIST_HIDDEN)

    drawpile_server = models.CharField(
        max_length=100,
        blank=True,
        help_text="The hostname of your drawpile server, if any. "
                  "(Include the port too, if not the default.)"
        )
    list_server = models.URLField(
        blank=True,
        help_text="The URL to your list server, if any."
        )
    homepage = models.URLField(
        blank=True,
        help_text="The URL to your homepage, if any."
        )

    guests_allowed = models.BooleanField(
        verbose_name="Guest users can log in",
        default=True)

    account_host = models.CharField(max_length=200, blank=True)

    require_group_membership = models.BooleanField(default=False)

    trust_members = models.BooleanField(
        default=False,
        verbose_name="Group members get the 'Trusted' flag"
    )

    host_policy = models.CharField(
        verbose_name="Who can host sessions?",
        max_length=16,
        choices=HOST_POLICY,
        default=HOST_EVERYONE
    )

    content_rating = models.CharField(max_length=16, choices=CONTENT_RATINGS, default=CONTENT_MIXED)

    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='communities.Membership'
    )

    status = models.CharField(
        max_length=32,
        choices=STATUSES,
        default=STATUS_SUBMITTED
    )
    review_message = models.TextField(blank=True)

    web_policy = models.CharField(
        verbose_name="How is joining via web browser handled?",
        max_length=16,
        choices=WEB_POLICY,
        default=WEB_DISABLED,
    )

    region = models.CharField(
        verbose_name="What's the rough region(s) of your server(s)?",
        max_length=255,
        default="",
    )

    class Meta:
        verbose_name_plural = "communities"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('communities:community', kwargs={'slug': self.slug})

    @property
    def moderators(self):
        return Membership.objects.filter(
            community=self,
            status__in=Membership.MOD_STATUSES
        ).order_by('joined').select_related('user')
    
    def is_member(self, user):
        return self.membership_set.active().filter(user=user).exists()

    def can_login(self, user):
        dp_accounts = self.account_host == 'drawpile.net'

        if self.guests_allowed or not dp_accounts:
            return True
        
        if not user.is_authenticated:
            return False
        
        return not self.require_group_membership or self.is_member(user)

    def can_admin(self, user):
        return user.is_authenticated and (
            user.has_perm('communities.change_community') or
            Membership.objects.filter(
                community=self, user=user,
                status=Membership.STATUS_ADMIN
            ).exists()
        )

    def can_see_memberlist(self, user):
        vis = self.memberlist_visibility
        return (
            vis == self.MEMBERLIST_VISIBLE or (
                user.is_authenticated and (
                    user.has_perm('communities.change_community') or
                    Membership.objects.filter(
                        community=self, user=user,
                        status__in=(
                            Membership.MEMBER_STATUSES
                            if vis == self.MEMBERLIST_PRIVATE
                            else Membership.MOD_STATUSES
                        )
                    ).exists()
                )
            )
        )


class MembershipQuerySet(models.QuerySet):
    def active(self):
        return self.filter(status__in=Membership.MEMBER_STATUSES)


class Membership(models.Model):
    STATUS_PENDING = 'pending'
    STATUS_INVITED = 'invited'
    STATUS_MEMBER = 'member'
    STATUS_MOD = 'mod'
    STATUS_ADMIN = 'admin'
    STATUS_BANNED = 'banned'
    STATUS_CHOICES = (
        (STATUS_PENDING, 'Pending approval'),
        (STATUS_INVITED, 'Invited'),
        (STATUS_MEMBER, 'Member'),
        (STATUS_MOD, 'Moderator'),
        (STATUS_ADMIN, 'Admin'),
        (STATUS_BANNED, 'Banned'),
        )
    MOD_STATUSES = (STATUS_MOD, STATUS_ADMIN)
    MEMBER_STATUSES = (STATUS_MEMBER,) + MOD_STATUSES

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    community = models.ForeignKey(
        Community,
        on_delete=models.CASCADE
    )
    joined = models.DateTimeField(auto_now_add=True)

    status = models.CharField(max_length=16, choices=STATUS_CHOICES)

    is_host = models.BooleanField(default=False)
    is_trusted = models.BooleanField(default=False)
    is_ghost = models.BooleanField(default=False)

    ban_reason = models.CharField(
        max_length=200,
        blank=True,
        help_text="Why this user was banned. "
                  "Visible to admins and this user only."
    )

    objects = MembershipQuerySet.as_manager()

    class Meta:
        unique_together = ('user', 'community')

    @property
    def is_mod(self):
        return self.status in self.MOD_STATUSES

    @property
    def is_admin(self):
        return self.status == self.STATUS_ADMIN

    @property
    def is_member(self):
        return self.status in self.MEMBER_STATUSES

    def get_mod_username(self):
        """Return the first Username associated with this
        user that has the Mod flag set, or the primary username
        if there is none.
        """
        return self.user.drawpilename_set\
            .filter(models.Q(name=self.user.username)|models.Q(is_mod=True))\
            .order_by('-is_mod')[0]

communities/templates/communities/age_gate.html
{% extends "communities/base.html" %}

{% block main %}
<section class="section">
<div class="container">

<div class="has-text-centered content">

<h2>
	{% if content_rating == "adult" %}
		<em>{{ object.title }}</em> is an NSFM-only community
	{% else %}
		Show NSFM sessions of <em>{{ object.title }}</em>
	{% endif %}
</h2>

<p>Sessions hosted here may contain artwork with serious topics that are not suitable for minors.</p>

<p>You must be at least eighteen years old to access it.</p>

<form action="{% url "communities:confirm-age" slug=object.slug %}" method="POST" class="disable-button-on-submit">
<p class="has-text-centered">
	{% csrf_token %}
	<button type="submit" class="button is-large is-danger is-outlined">I am over 18 years old</button>
	{% if content_rating == "adult" %}
		<a href="{% url "communities:frontpage" %}" class="button is-large">Go back</a>
	{% else %}
		<a href="{% url "communities:community" slug=object.slug %}" class="button is-large">Go back</a>
	{% endif %}
</p>
</form>

</div>

</div> {# /.container #}
</section>
{% endblock %}

communities/templates/communities/base.html
{% extends "base.html" %}

{% load static %}

{% block title %}Communities - {{ block.super }}{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static "css/communities.css" %}">
{% endblock %}

communities/templates/communities/community.html
{% extends "communities/base.html" %}

{% load commonmark %}
{% load static %}
{% load widget_tweaks %}
{% load cando %}

{% block extrascripts %}
<script src="{% static "js/sessionlist.min.js" %}"></script>
<script src="{% static "js/community.min.js" %}"></script>
{% endblock %}

{% block main %}
{% if object.status != 'accepted' %}
<section class="hero {% if object.status == 'rejected' %}is-danger{% else %}is-warning{% endif %}">
	<div class="hero-body">
		<div class="container">
{% if object.status == 'submitted' %}
			<p>This submission is awaiting review by site admins.</p>

			{% if review_form %}
			<p>Hey, <i>you're a site admin!</i> You can review this page:</p>
			<form method="POST" action="{% url "communities:review" slug=object.slug %}" class="disable-button-on-submit">
				{% include "components/radio-field.html" with field=review_form.verdict %}
				{% with field=review_form.comment %}<div class="field">
					<label class="label" for="{{ field.id_for_label }}">{{ field.label }}</label>
					<div class="control">{% render_field field class+="textarea" rows=2 %}</div>
				</div>{% endwith %}

				<p><input type="submit" class="button is-primary" value="Review"></p>
				{% csrf_token %}
			</form>
			{% endif %}
{% elif object.status == 'resubmit' %}
			<p>Admins have requested changes before this community can be published:</p>
			<p>{{ object.review_message }}</p>
{% elif object.status == 'rejected' %}
			<p>This community has been rejected:</p>
			<p>{{ object.review_message }}</p>
{% endif %}
		</div>
	</div>
</section>
{% endif %}

<section class="section">
<div class="container">

<div class="notification content">
	<p>
		Community servers are <em>external servers and drawing sessions</em> not provided by Drawpile itself. Check their rules and policies before using them. If a community or session violates any guidelines, use <a href="#abuse-report-button">the "report community" button below</a> or any of the contact options <a href="/help/">on the help page</a> to report it.
	</p>
</div>

<div class="content">
	<p><a href="{% url "communities:frontpage" %}">&larr; Back to community list</a></p>
</div>

<h2 class="title">{{ object.title }}</h2>

<div id="community-page-content">

<div id="community-page-main">
<div class="content">
{{ object.full_description|commonmark_safe }}

<h3>Rules</h3>

<p>The rules from <a href="{% url "communities:ccg" %}">the common community guidelines</a> apply to this and all other communities.</p>

{{ object.rules|commonmark_safe }}

</div>{# /.content #}


</div>{# /#community-page-main #}

<div id="community-box">
	<div class="community-banner">
		<img src="{{ object.badge.url }}" alt="">
	</div>

	<div class="box-section has-text-centered">
		{% if object.homepage %}
		<a class="button is-link is-medium" href="{{ object.homepage }}{% if object.content_rating != 'sfw' and am_adult %}{% if "?" in object.homepage %}&{% else %}?{% endif %}nsfm=true{% endif %}">
			<span class="icon"><i class="fas fa-home"></i></span>
			<span>Website</span>
			</a>
		{% endif %}
		{% if object|can:user|use:"login" %}
		<a class="button is-primary is-medium" href="#community-session-list">
			<span class="icon"><i class="fas fa-sign-in-alt"></i></span>
			<span>Sessions</span>
		</a>
		{% endif %}

	</div>

	<div class="box-section content">
		<p>
			{% if object.guests_allowed %}
				{% if object.host_policy == 'all-host' %}
					Anyone join and host sessions on this server without an account.
				{% elif object.host_policy == 'account-host' %}
					Anyone can join sessions on this server without an account. Hosting sessions requires an account.
				{% elif object.host_policy == 'member-host' %}
					Anyone can join sessions on this server without an account. Hosting sessions requires an account and you must be a member of this community.
				{% else %}
					Anyone can join sessions on this server without an account. Hosting sessions is limited to specific users.
				{% endif %}
			{% else %}
				{% if object.host_policy == 'all-host' or object.host_policy == 'account-host' %}
					An account is required to join and host sessions on this server.
				{% elif object.host_policy == 'member-host' %}
					An account is required to join sessions on this server. Hosting sessions also requires you to be a member of this community.
				{% else %}
					An account is required to join sessions on this server. Hosting sessions is limited to specific users.
				{% endif %}
			{% endif %}
		</p>
		<p>
			{% if object.account_host %}
				{% if object.require_group_membership %}
					You can use <strong>{{ object.account_host }}</strong> accounts on this server and you <strong>must be a member of this group</strong>.
				{% else %}
					You can use <strong>{{ object.account_host }}</strong> accounts on this server.
				{% endif %}
			{% endif %}
		</p>
		<p>
			{% if object.web_policy == 'manual' %}
				Sessions approved by the server owner can be joined via web browser.
			{% elif object.web_policy == 'passworded' %}
				Sessions with a password can be joined via web browser.
			{% elif object.web_policy == 'open' %}
				Any session can be joined via web browser.
			{% else %}
				This server does not support joining sessions via web browser.
			{% endif %}
		</p>
		{% if object.region %}
			<p>
				Server region: {{ object.region }}. Regions closer to you may have better latency.
			</p>
		{% endif %}
	</div>

	{% if object.content_rating == 'sfw' %} <div class="box-section content-rating sfw">NSFM forbidden</div>
	{% elif object.content_rating == 'mixed' %}<div class="box-section content-rating mixed">NSFM permitted if marked</div>
	{% else %}<div class="box-section content-rating nsfw">NSFM only</div>
	{% endif %}

	{% if user.is_authenticated %}
	{% if membership.status or object.group_policy != 'invite-only' %}
	<div class="box-section has-text-centered">
		{% if not membership.status or membership.status == 'invited' %}
			<p><button class="button is-primary is-medium" disabled id="join-group-button" data-url="{% url "api:community-join" slug=object.slug %}">
				<span class="icon"><i class="fas fa-user-plus"></i></span>
				<span>{% if membership.status == 'invited' %}Accept join invitation{% else %}Join group{% endif %}</span>
			</button></p>
		{% elif membership.status != 'banned' %}
			<p><button class="button is-danger is-small" disabled id="leave-group-button" data-url="{% url "api:community-member" slug=object.slug user=user.username%}" {% if membership.status == 'admin' %}data-admin="true"{% endif %}>
				<span class="icon"><i class="fas fa-user-minus"></i></span>
				<span>{% if membership.status == 'invited' %}Refuse invitation{% elif membership.status == 'pending' %}Cancel join petition{% else %}Leave group{% endif %}</span>
			</button></p>
		{% else %}
			<div class="notification is-danger">
				<p>
					<span class="icon"><i class="fas fa-ban"></i></span>
					<span>You've been banned from this group.</span>
				</p>
				<blockquote>{{ membership.ban_reason }}</blockquote>
			</div>
		{% endif %}

		{% if object.memberlist_visibility != "hidden" %}
		{% if membership.is_member or object.memberlist_visibility == "visible" %}
		<p style="margin-top: 15px"><a href="{% url 'communities:memberlist' slug=object.slug %}" target="_blank" rel="noopener" class="smallNewWindow">Member list</a></p>
		{% endif %}
		{% endif %}
	</div>
	{% endif %}
	{% endif %}

	<div class="box-section content">
		<p><b>Moderators</b></p>
		{% for mod_member in object.moderators %}{% with mod=mod_member.get_mod_username %}
			<span class="avatar-user">
			{% if mod.avatar %}
				<img class="avatar" src="{{ mod.avatar.url }}" alt="">
			{% else %}
				<span class="avatar avatar-placeholder"></span>
			{% endif %}
				<span class="username">{{ mod.name }}</span>
			</span>
		{% endwith %}{% endfor %}
	</div>

	{% if membership.is_admin or perms.communities.change_community %}
	<div class="box-section">
		<p><b>Admin toolbox</b></p>
		<p>
			<a href="{% url "communities:edit" slug=object.slug %}" class="button is-primary is-large" title="Edit">
				<span class="icon"><i class="fas fa-edit"></i></span>
			</a>
			<a href="{% url "communities:memberlist" slug=object.slug %}?edit" target="_blank" rel="noopener" class="button is-primary is-large smallNewWindow" title="Edit member list">
				<span class="icon"><i class="fas fa-users"></i></span>
			</a>
			<a href="{% url "communities:server-help" slug=object.slug %}" class="button is-info is-large" title="Server setup help">
				<span class="icon"><i class="fas fa-info"></i></span>
			</a>
			{% if user.is_staff and perms.communities.change_community %}
			<a href="{% url "admin:communities_community_change" object.id %}" class="button is-danger is-large" title="Show in admin site">
				<span class="icon"><i class="fas fa-hammer"></i></span>
			</a>
			{% endif %}
		</p>
	</div>
	{% endif %}

	{% if can_report %}
	<div class="has-text-centered">
		<p><button disabled class="button is-text" id="abuse-report-button" data-url="{% url "api:community-report-abuse" slug=object.slug %}">
			<span class="icon"><i class="fas fa-circle-notch fa-spin"></i></span>
			<span>Report community</span>
		</button></p>
	</div>
	{% endif %}

</div>{# /#community-box #}

{% if object.list_server %}
<div id="community-session-list">
	<h3 class="is-size-4" style="clear: right">Sessions</h3>

	{% if object|can:user|use:"login" %}
	<div id="community-session-notice" class="notification content is-hidden">
		<p>
			To add these listings to Drawpile's server browser, go to the <strong>Browse</strong> page, click <strong>Add Server</strong> at the bottom and enter <code>{{ object.list_server }}</code>. <span id="community-session-notice-link" class="is-hidden">If you have Drawpile installed, you can also <a href="drawpile://{% if object|can:user|use:"login" %}{{ object.drawpile_server }}{% endif %}/?list-server={{ object.list_server }}">click here to add it</a>.</span>
		</p>
	</div>
	{% endif %}

	<div id="community-session-list-view" class="has-text-centered" data-url="{{ object.list_server }}/sessions/{% if object.content_rating != 'sfw' and am_adult %}?nsfm=true{% endif %}" {% if object.content_rating == 'mixed' and not am_adult %}data-nsfmopt="true"{% endif %}>
		<button class="button is-link" disabled>
			<span class="icon"><span class="fa fa-circle-notch fa-spin"></span></span>
			<span>Show Sessions</span>
		</button>
		<p class="help">This will load sessions from this community's external server.</p>
	</div>
</div>
{% endif %}

</div>{# /#community-page-content #}

</div> {# /.container #}
</section>
{% endblock %}

communities/templates/communities/ych.html
{% extends "communities/base.html" %}

{% load commonmark %}

{% block main %}
<section class="section">
<div class="container">

<h2 class="title">Your Community Here &ndash; listing your community at drawpile.net</h2>

<div class="content">
{% filter commonmark_full %}
If you run a Drawpile server of your own, you can have it listed here on this website.
If you do not yet have a server of your own, but would like to run one, see the
[dedicated server HOWTO](/help/server-howto/) for instructions.

By having a community page at drawpile.net, you get a place for new users to discover
your server and access to ready-made user management features.

If your server uses drawpile.net accounts, you will be able to:

 * Restrict login to select users
 * Grant moderator status to specific users
 * Ban users accounts

For a safe and consistent experience, communities listed at drawpile.net should adhere to the
[common community guidelines]({% url "communities:ccg" %}). Do note that the software itself
is free to use for any purpose and you *may* create a Drawpile server that will not
be listed here and does not have to follow these rules.

{% endfilter %}

<p class="has-text-centered">
	<a href="{% url "communities:submit" %}" class="button is-large is-primary">Submit your community</a>
</p>
</div>{# /.content #}

</div> {# /.container #}
</section>
{% endblock %}