dpauth/urls.py
from django.urls import path, re_path
from . import views

app_name = "auth"
urlpatterns = [
    path("", views.AuthUsernamesView.as_view(), name="usernames"),
    re_path(r"^finish/(?P<name>.+)/$", views.AuthFinishView.as_view(), name="finish"),
    path("login/", views.AuthLoginView.as_view(), name="login"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
    path("ban-analyzer/", views.BanAnalyzerView.as_view(), name="ban-analyzer"),
    path(
        "monitor-manager/", views.MonitorManagerView.as_view(), name="monitor-manager"
    ),
    path(
        "monitor-manager/restart",
        views.MonitorManagerRestartView.as_view(),
        name="monitor-manager-restart",
    ),
]

drawpile/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf import settings

from templatepages.views import DocumentationDetailView, TemplatePageView


class DonationRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        try:
            lang = self.request.GET["lang"]
            if lang and lang.startswith("de_"):
                return self.url + "de/"
        except:
            pass
        return self.url


urlpatterns = [
    path('_admin/', admin.site.urls),
    path('api/', include('drawpile.api_urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('dpusers.urls')),
    path('auth/', include('dpauth.urls')),
    path('communities/', include('communities.urls')),
    path('invites/', include('invites.urls')),
    path('ban/', RedirectView.as_view(
        url='/communities/drawpile.net/ban/', permanent=True)),
    path('readonly/', TemplateView.as_view(template_name='readonly.html')
        if settings.DRAWPILE_READONLY_SITE
        else RedirectView.as_view(url='/', permanent=False)),
    path('discord/', RedirectView.as_view(url='https://discord.gg/VHRDh2fKnc', permanent=True)),
    path('fedi/', RedirectView.as_view(url='https://floss.social/@drawpile', permanent=True)),
    path('matrix/', RedirectView.as_view(url='https://matrix.to/#/#drawpile:matrix.org', permanent=True)),
    path('localhosthelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/common/hosting#builtin-server', permanent=True)),
    path('pubrules/', RedirectView.as_view(url='/communities/drawpile.net/ccg/', permanent=True)),
    path('sharedarraybufferhelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/tech/browser#sharedarraybuffer-issues', permanent=True)),
    path('lgm/', TemplateView.as_view(template_name='lgm.html')),
    path('namecheckbot/', TemplateView.as_view(template_name='namecheckbot.html')),
    path('donate/', DonationRedirectView.as_view(url="https://donate.drawpile.org/", permanent=True)),
    path('', TemplateView.as_view(template_name='pages/index.html')),
]

if hasattr(settings, "DRAWPILE_IMPRESSUM"):
    urlpatterns += path('impressum/', TemplateView.as_view(template_name='impressum.html')),

if hasattr(settings, "DRAWPILE_PRIVACY_POLICY"):
    urlpatterns += path('privacy/', TemplateView.as_view(template_name='privacy.html')),

if hasattr(settings, "DRAWPILE_TOS"):
    urlpatterns += path('tos/', TemplateView.as_view(template_name='tos.html')),

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    path('docs/<slug:slug>/', DocumentationDetailView.as_view(), name='documentation-detail'),
    re_path(r'^(?P<path>.*)/$', TemplatePageView.as_view()),
]

news/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.NewsListView.as_view(), name="list"),
    path('feed.atom', views.NewsFeed(), name="atom-feed"),
    path('release-2.3.0-beta.1/', RedirectView.as_view(url="/news/release-2.3.0-beta.2/", permanent=True)),
    path('<slug>/', views.NewsDetailView.as_view(), name='detail'),
]

news/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.core.validators import RegexValidator

class PostManager(models.Manager):
    def visible(self):
        return self.get_queryset().filter(is_visible=True, publish__lte=timezone.now())

class Post(models.Model):
    slug = models.CharField(
        max_length=50,
        unique=True,
        validators=[RegexValidator(r'^[-.\w]+$')]
        )
    publish = models.DateTimeField()
    is_visible = models.BooleanField(default=False)
    title = models.CharField(max_length=200)
    author_name = models.CharField(max_length=200)
    show_author = models.BooleanField(default=False)

    intro = models.TextField()
    readmore = models.TextField(blank=True)

    objects = PostManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('news:detail', kwargs={'slug': self.slug})

news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.syndication.views import Feed
from django.utils.feedgenerator import Atom1Feed

from . import models

from commonmark import commonmark


class NewsListView(ListView):
    paginate_by=5

    def get_queryset(self):
        return models.Post.objects.visible()


class NewsDetailView(DetailView):
    def get_queryset(self):
        qs = models.Post.objects
        if not self.request.user.has_perm('news.change_post'):
            qs = qs.visible()
        else:
            qs = qs.all()
        return qs


class NewsFeed(Feed):
    feed_type = Atom1Feed
    title = "Drawpile.net news"
    link = '/news/'

    def items(self):
        return models.Post.objects.visible()[:5]

    def item_title(self, item):
        return item.title

    def item_author_name(self):
        return "Drawpile.net"

    def item_description(self, item):
        return commonmark(item.intro)

    def item_pubdate(self, item):
        return item.publish

news/templates/news/__post.html
<article>{% load commonmark %}
	{% if post_latest %}
		<h2 class="title">
			{% if readmore %}
			Latest News: {{ post.title }}
			{% else %}
			<a href="{{ post.get_absolute_url }}" title="Show full post">Latest News: {{ post.title }}</a>
			{% endif %}
		</h2>
		<h3 class="subtitle">{{ post.publish|date }}{% if post.show_author %} by {{ post.author_name }}{% endif %}</h3>
	{% else %}
		<h1 class="title">
			{% if readmore %}
			{{ post.title }}
			{% else %}
			<a href="{{ post.get_absolute_url }}" title="Show full post">{{ post.title }}</a>
			{% endif %}
		</h1>
		<h2 class="subtitle">{{ post.publish|date }}{% if post.show_author %} by {{ post.author_name }}{% endif %}</h2>
	{% endif %}
	<div class="content">
	{{ post.intro|commonmark_full }}
	{% if readmore %}
	{{ post.readmore|commonmark_full }}
	{% else %}
	<p><a href="{{ post.get_absolute_url }}">Read more...</a></p>
	{% endif %}
	</div>
</article>

news/templates/news/post_detail.html
{% extends "base.html" %}

{% block extrameta %}
<meta property="og:type" content="website">
<meta property="og:title" content="{{ post.title }} - Drawpile">
<meta property="og:description" content="News from {{ post.publish|date }} by {{ post.author_name }}">
<meta property="og:image" content="https://drawpile.net/files/og/logo.png">
{% endblock %}

{% block title %}{{ post.title }} - {{ block.super }}{% endblock %}

{% block main %}

<section class="section">
<div class="container">
{% if not object.is_visible %}
	<div class="notification is-danger has-text-centered">
		Hidden
	</div>
{% endif %}

	{% include "news/__post.html" with readmore='True' %}

</div>{# ./container #}
</section>

{% endblock main %}

news/templates/news/post_list.html
{% extends "base.html" %}

{% block title %}News - {{ block.super }}{% endblock %}

{% block extrahead %}
	<link rel="alternate" type="application/atom+xml" title="Drawpile.net news" href="{% url "news:atom-feed" %}" />
{% endblock %}

{% block main %}

<section class="section">
<div class="container">

{% for post in page_obj %}
	{% include "news/__post.html" %}
	<hr>
{% endfor %}

{% include "components/paginator.html" %}

</div>{# ./container #}
</section>

{% endblock %}