dpauth/urls.py
from django.urls import path, re_path
from . import views

app_name = "auth"
urlpatterns = [
    path("", views.AuthUsernamesView.as_view(), name="usernames"),
    re_path(r"^finish/(?P<name>.+)/$", views.AuthFinishView.as_view(), name="finish"),
    path("login/", views.AuthLoginView.as_view(), name="login"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
    path("ban-analyzer/", views.BanAnalyzerView.as_view(), name="ban-analyzer"),
    path(
        "monitor-manager/", views.MonitorManagerView.as_view(), name="monitor-manager"
    ),
    path(
        "monitor-manager/restart",
        views.MonitorManagerRestartView.as_view(),
        name="monitor-manager-restart",
    ),
]

dpusers/urls.py
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from django.urls import reverse_lazy
from django.urls import path, re_path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('tos/', RedirectView.as_view(url='/tos/', permanent=False)),
]

if settings.DRAWPILE_READONLY_SITE:
    urlpatterns += [
        re_path(r'.*', RedirectView.as_view(url='/readonly/', permanent=False)),
    ]
else:
    urlpatterns += [
        path('signup/', views.SignupView.as_view(), name='signup'),
        path('finish-signup/', views.FinishSignupView.as_view(), name='finish-signup'),

        path('profile/', views.AccountView.as_view(), name='profile-account'),
        path('profile/email_change/', views.EmailChangeView.as_view(), name='profile-emailchange'),
        path('profile/email_change/confirm/', views.ConfirmEmailChangeView.as_view(), name='profile-emailchange-confirm'),
        path('profile/usernames/', views.UsernameView.as_view(), name='profile-usernames'),

        path('delete/', views.DeleteAccountView.as_view(), name='delete-account'),

        # Views provided by Django:
        path('login/', auth_views.LoginView.as_view(), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),

        path(
            'profile/password_change/',
            auth_views.PasswordChangeView.as_view(
                template_name='users/password_change.html',
                success_url=reverse_lazy('users:password_change_done'),
                extra_context={'profile_page': 'password_change'}
            ),
            name='password_change'
        ),
        path(
            'profile/password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(
                template_name='users/password_change_done.html',
                extra_context={'profile_page': 'password_change'}
                ),
            name='password_change_done'
        ),
        path(
            'password_reset/',
            views.ResetPasswordView.as_view(),
            name='password_reset'
        ),
        path(
            'password_reset/done/',
            auth_views.PasswordResetDoneView.as_view(
                template_name='registration/reset_password_done.html'
            ),
            name='password_reset_done'
        ),
        path(
            'reset/<uidb64>/<token>/',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='registration/reset_password_confirm.html',
                success_url=reverse_lazy('users:password_reset_complete')
            ),
            name='password_reset_confirm'
        ),
        path(
            'reset/done/',
            auth_views.PasswordResetCompleteView.as_view(
                template_name='registration/reset_password_complete.html'
            ),
            name='password_reset_complete'
        ),
    ]

drawpile/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf import settings

from templatepages.views import DocumentationDetailView, TemplatePageView


class DonationRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        try:
            lang = self.request.GET["lang"]
            if lang and lang.startswith("de_"):
                return self.url + "de/"
        except:
            pass
        return self.url


urlpatterns = [
    path('_admin/', admin.site.urls),
    path('api/', include('drawpile.api_urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('dpusers.urls')),
    path('auth/', include('dpauth.urls')),
    path('communities/', include('communities.urls')),
    path('invites/', include('invites.urls')),
    path('ban/', RedirectView.as_view(
        url='/communities/drawpile.net/ban/', permanent=True)),
    path('readonly/', TemplateView.as_view(template_name='readonly.html')
        if settings.DRAWPILE_READONLY_SITE
        else RedirectView.as_view(url='/', permanent=False)),
    path('discord/', RedirectView.as_view(url='https://discord.gg/VHRDh2fKnc', permanent=True)),
    path('fedi/', RedirectView.as_view(url='https://floss.social/@drawpile', permanent=True)),
    path('matrix/', RedirectView.as_view(url='https://matrix.to/#/#drawpile:matrix.org', permanent=True)),
    path('localhosthelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/common/hosting#builtin-server', permanent=True)),
    path('pubrules/', RedirectView.as_view(url='/communities/drawpile.net/ccg/', permanent=True)),
    path('sharedarraybufferhelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/tech/browser#sharedarraybuffer-issues', permanent=True)),
    path('lgm/', TemplateView.as_view(template_name='lgm.html')),
    path('namecheckbot/', TemplateView.as_view(template_name='namecheckbot.html')),
    path('donate/', DonationRedirectView.as_view(url="https://donate.drawpile.org/", permanent=True)),
    path('', TemplateView.as_view(template_name='pages/index.html')),
]

if hasattr(settings, "DRAWPILE_IMPRESSUM"):
    urlpatterns += path('impressum/', TemplateView.as_view(template_name='impressum.html')),

if hasattr(settings, "DRAWPILE_PRIVACY_POLICY"):
    urlpatterns += path('privacy/', TemplateView.as_view(template_name='privacy.html')),

if hasattr(settings, "DRAWPILE_TOS"):
    urlpatterns += path('tos/', TemplateView.as_view(template_name='tos.html')),

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    path('docs/<slug:slug>/', DocumentationDetailView.as_view(), name='documentation-detail'),
    re_path(r'^(?P<path>.*)/$', TemplatePageView.as_view()),
]

news/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.NewsListView.as_view(), name="list"),
    path('feed.atom', views.NewsFeed(), name="atom-feed"),
    path('release-2.3.0-beta.1/', RedirectView.as_view(url="/news/release-2.3.0-beta.2/", permanent=True)),
    path('<slug>/', views.NewsDetailView.as_view(), name='detail'),
]

dpusers/views.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.views.generic import TemplateView, FormView, UpdateView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.db import transaction
from django.utils import timezone
from dpauth.models import Username
from dpauth.settings import extauth_settings
from communities.models import Membership
from django.contrib.auth import views as auth_views
from .models import PendingDeletion, SentEmail
from .forms import (
    SignupForm,
    FinishSignupForm,
    EmailChangeForm,
    ConfirmEmailChangeForm,
    ConfirmDeleteAccountForm,
    ResetPasswordForm,
)
from .token import (
    make_signup_token,
    parse_signup_token,
    make_emailchange_token,
    parse_emailchange_token,
)
from .mail import send_template_mail

import logging

logger = logging.getLogger(__name__)


def _allow_username(username):
    for regex in settings.DRAWPILE_USERNAME_REJECTIONS:
        if regex.search(username):
            return False
    return True


def _allow_email(email):
    for regex in settings.DRAWPILE_EMAIL_REJECTIONS:
        if regex.search(email):
            return False
    return True


def _is_email_maintenance(request):
    return settings.DRAWPILE_EMAIL_MAINTENANCE and request.GET.get("override") != settings.DRAWPILE_EMAIL_MAINTENANCE_OVERRIDE


class SignupView(FormView):
    """New user signup: first phase.

    This doesn't save anything in the database yet. Instead, it generates
    a token for the next phase, which actually creates the account.
    The token is mailed to the given email address to ensure the
    address is real.
    """

    form_class = SignupForm
    success_url = reverse_lazy("users:finish-signup")

    def get_template_names(self):
        if _is_email_maintenance(self.request):
            return ["registration/signup_maintenance.html"]
        else:
            return ["registration/signup.html"]

    def form_valid(self, form):
        cd = form.cleaned_data
        username = cd["username"]
        email = cd["email"]
        if _allow_username(username) and _allow_email(email):
            self.send_signup_token(username, email)
        else:
            logger.warning("Not sending signup mail for '%s' to '%s'", username, email)
        return super().form_valid(form)

    def send_signup_token(self, username, email):
        token = make_signup_token(username, email)
        protocol = "https" if self.request.is_secure() else "http"
        domain = self.request.get_host()
        logger.info("Sending signup token mail for '%s' to '%s'", username, email)
        SentEmail.store_sent_email(SentEmail.EmailType.SIGNUP, email)
        send_template_mail(
            email,
            "registration/mail/signup.txt",
            "Complete your drawpile.net account creation",
            {
                "SIGNUP_URL": protocol
                + "://"
                + domain
                + str(self.success_url)
                + "?token="
                + token,
            },
        )


class FinishSignupView(FormView):
    """Complete the signup and create a new user account.

    Finishing the signup process requires a valid token that
    was generated in the first phase.
    """

    template_name = "registration/finish-signup.html"
    form_class = FinishSignupForm
    success_url = "/"

    def get_initial(self):
        return {"token": self.request.GET.get("token", "")}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            token = self.request.POST.get("token", "")
        else:
            token = self.request.GET.get("token", "")

        if not token:
            ctx["noToken"] = True
        else:
            try:
                ctx["token"] = parse_signup_token(token)
            except ValidationError as e:
                ctx["tokenError"] = e.message

        return ctx

    def form_valid(self, form):
        cd = form.cleaned_data
        token = parse_signup_token(cd["token"])

        logger.info("%s (%s) signup complete", token["name"], token["email"])
        with transaction.atomic():
            user = get_user_model().objects.create_user(
                token["name"], token["email"], cd["password"]
            )
            Username.objects.create(user=user, name=token["name"])

        user = authenticate(
            self.request, username=user.username, password=cd["password"]
        )
        login(self.request, user)

        return super().form_valid(form)


class AccountView(LoginRequiredMixin, TemplateView):
    """General account settings"""

    template_name = "users/account.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({"profile_page": "account"})
        return ctx

    def post(self, request):
        action = request.POST.get("action", "")
        if action == "change-email":
            print("Changing email")

        return redirect("users:profile-account")


class EmailChangeView(LoginRequiredMixin, FormView):
    """Account email address changing view.
    Like the signup, this is a two-phase process: first, a confirmation
    token is generated and sent to the new email address.
    In the second phase, when the user has proven that they have access
    to the new email address by clicking on the confirmation link,
    the address is actually changed.
    """

    template_name = "users/email_change.html"
    form_class = EmailChangeForm
    success_url = reverse_lazy("users:profile-emailchange-confirm")

    def get_template_names(self):
        if _is_email_maintenance(self.request):
            return ["users/email_change_maintenance.html"]
        else:
            return ["users/email_change.html"]

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({"profile_page": "account"})
        return ctx

    def form_valid(self, form):
        cd = form.cleaned_data
        user = self.request.user
        email = cd["email"]
        if _allow_email(email):
            token = make_emailchange_token(user.id, email)

            protocol = "https" if self.request.is_secure() else "http"
            domain = self.request.get_host()

            logger.info(
                "Sending email change confirmation for '%s' (%s) from '%s' to '%s'",
                user.username,
                user.id,
                user.email,
                email,
            )
            SentEmail.store_sent_email(SentEmail.EmailType.EMAIL_CHANGE, email)
            send_template_mail(
                email,
                "users/mail/change_email.txt",
                "Changing your drawpile.net account email address",
                {
                    "CHANGE_URL": protocol
                    + "://"
                    + domain
                    + str(self.success_url)
                    + "?token="
                    + token,
                },
            )
        else:
            logger.warning(
                "Not sending email change confirmation for '%s' (%s) from '%s' to '%s'",
                user.username,
                user.id,
                user.email,
                email,
            )

        return super().form_valid(form)


class ConfirmEmailChangeView(LoginRequiredMixin, FormView):
    """Change an account's email address.
    This requires the token that was generated in the first phase.
    Additionally, to prevent someone from taking over an account that was
    left logged in, this also requires the current password.
    """

    template_name = "users/email_change_confirm.html"
    form_class = ConfirmEmailChangeForm
    success_url = reverse_lazy("users:profile-account")

    def get_initial(self):
        return {"token": self.request.GET.get("token", "")}

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            token = self.request.POST.get("token", "")
        else:
            token = self.request.GET.get("token", "")

        if not token:
            ctx["noToken"] = True
        else:
            try:
                ctx["token"] = parse_emailchange_token(token)
            except ValidationError as e:
                ctx["tokenError"] = e.message

        ctx["profile_page"] = "account"
        return ctx

    def form_valid(self, form):
        cd = form.cleaned_data
        token = parse_emailchange_token(cd["token"])

        logger.info("Changing user #%s email to %s", token["user"], token["email"])
        user = get_user_model().objects.get(id=token["user"])
        user.email = token["email"]
        user.save()

        return super().form_valid(form)


class UsernameView(LoginRequiredMixin, TemplateView):
    template_name = "users/usernames.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        mod_status = []
        mod_available = False
        ghost_available = False
        if self.request.user.has_perm("dpauth.moderator"):
            mod_available = True
            if self.request.user.has_perm("dpauth.ghost"):
                mod_status.append("Global moderator and ghost status.")
                ghost_available = True
            else:
                mod_status.append("Global moderator status.")

        memberships = Membership.objects.filter(

dpusers/templates/users/account.html
{% extends "users/base.html" %}

{% block profile_subtitle %}Account details{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-header">Email address</div>
	<div class="message-body">
		<div class="content">
			<p>{{ user.email }}</p>
		</div>
		<div class="field">
			<div class="control">
				<a href="{% url 'users:profile-emailchange' %}" class="button is-danger">Change</a>
			</div>
		</div>
	</div>
</div>

<div class="message">
	<div class="message-header">Delete account</div>
	<div class="message-body">
		<div class="content">
			<p>Delete your account and all its associated data.</p>
		</div>
		<div class="field">
			<div class="control">
				<a href="{% url 'users:delete-account' %}" class="button is-danger">Delete account</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

dpusers/templates/users/base.html
{% extends "base.html" %}

{% block title %}User account - {{ block.super }}{% endblock %}

{% block main %}

<section class="section">
<div class="container">

	<div class="columns">
		<div class="column is-one-fifth">
			<aside class="menu">
				<ul class="menu-list">
					<li><a href="{% url 'users:profile-account' %}" {% if profile_page == 'account' %}class="is-active"{% endif %}>Account</a></li>
					<li><a href="{% url 'users:password_change' %}" {% if profile_page == 'password_change' %}class="is-active"{% endif %}>Password</a></li>
					<li><a href="{% url 'users:profile-usernames' %}" {% if profile_page == 'usernames' %}class="is-active"{% endif %}>Usernames</a></li>
				</ul>
			</aside>
		</div>{# /.column #}
		<div class="column">
			{% block profile_main %}{% endblock %}
		</div>{# /.column #}
	</div>{# /.columns #}

</div>{# ./container #}
</section>

{% endblock %}

dpusers/templates/users/delete_account_confirm.html
{% extends "users/base.html" %}

{% load widget_tweaks %}

{% block profile_subtitle %}Account deletion{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-header">Delete account</div>
	<div class="message-body">
		<form method="post" class="disable-button-on-submit">
			{% if form.non_field_errors %}
				<div class="notification is-danger">{{ form.non_field_errors }}</div>
			{% endif %}

		<div class="field">
			<label class="label" for="{{ form.password.auto_id }}">Enter your password to confirm account deletion</label>
			<div class="control">
				{% render_field form.password class+="input" %}
			</div>
			{% if form.errors.password %}<div class="help is-danger">{{ form.errors.password }}</div>{% endif %}
			<div class="content">
				<p><span class="fa fa-exclamation-triangle"></span> You will not be able to use the same email address to register again for 30 days.</p>
			</div>
		</div>{# /.field #}

		<div class="field is-grouped">
			<div class="control">
				<input type="submit" class="button is-danger" value="Delete">
			</div>
			<div class="control">
				<a href="{% url 'users:profile-account' %}" class="button is-text">Cancel</a>
			</div>
		</div>{# /.field #}

		{{ form.token }}
		{% csrf_token %}
		</form>
	</div>{# /.message-body #}
</div>

{% endblock %}

dpusers/templates/users/email_change.html
{% extends "users/base.html" %}

{% load widget_tweaks %}

{% block profile_subtitle %}Account details{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-header">Email address</div>
	<div class="message-body">
		<form method="post" class="disable-button-on-submit">
		{% if form.non_field_errors %}
		<div class="notification is-danger">{{ form.non_field_errors }}</div>
		{% endif %}
		<div class="field">
			<label class="label">Current email address</label>
			<div class="control">
				<input class="input" type="text" value="{{ user.email }}" disabled>
			</div>
		</div>{# /.field #}

		<div class="field">
			<label class="label" for="{{ form.email.auto_id }}">New email address</label>
			<div class="control">
				{% render_field form.email class+="input" %}
			</div>
			{% if form.errors.email %}<div class="help is-danger">{{ form.errors.email }}</div>{% endif %}
		</div>{# /.field #}

		<div class="field">
			A confirmation link will be sent to the new address.
		</div>

		<div class="field is-grouped">
			<div class="control">
				<input type="submit" class="button is-danger" value="Change">
			</div>
			<div class="control">
				<a href="{% url 'users:profile-account' %}" class="button is-text">Cancel</a>
			</div>
		</div>{# /.field #}

		{% csrf_token %}
		</form>
	</div>{# /.message-body #}
</div>

{% endblock %}

dpusers/templates/users/email_change_confirm.html
{% extends "users/base.html" %}

{% load widget_tweaks %}

{% block profile_subtitle %}Account details{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-header">Email address</div>
	<div class="message-body">
		{% if noToken %}
		<div class="content">
			<p>
				A confirmation link has been sent to the new email address.
				Click on the link inside to finish the signup process.
			</p>
			<p>
				It may take a few minutes for the email to arrive and it may
				land in your spam folder. If it doesn't arrive at all, <a
				href="/help/" target="_blank">ask for help on Discord or
				IRC</a>. An admin can send out the confirmation link manually.
			</p>
		</div>
		{% else %}

		<form method="post" class="disable-button-on-submit">
			{% if form.non_field_errors %}
				<div class="notification is-danger">{{ form.non_field_errors }}</div>
			{% elif tokenError %}
				<div class="notification is-danger">{{ tokenError }}</div>
			{% endif %}

		<div class="field">
			<label class="label">Current email address</label>
			<div class="control">
				<input class="input" type="text" value="{{ user.email }}" disabled>
			</div>
		</div>{# /.field #}

		<div class="field">
			<label class="label">New email address</label>
			<div class="control">
				<input class="input" type="text" value="{{ token.email }}" disabled>
			</div>
		</div>{# /.field #}

		<div class="field">
			<label class="label" for="{{ form.password.auto_id }}">Enter your password to confirm email change</label>
			<div class="control">
				{% render_field form.password class+="input" %}
			</div>
			{% if form.errors.password %}<div class="help is-danger">{{ form.errors.password }}</div>{% endif %}
		</div>{# /.field #}

		<div class="field is-grouped">
			<div class="control">
				<input type="submit" class="button is-danger" value="Change">
			</div>
			<div class="control">
				<a href="{% url 'users:profile-account' %}" class="button is-text">Cancel</a>
			</div>
		</div>{# /.field #}

		{{ form.token }}
		{% csrf_token %}
		</form>
		{% endif %}
	</div>{# /.message-body #}
</div>

{% endblock %}

dpusers/templates/users/email_change_maintenance.html
{% extends "users/base.html" %}

{% load widget_tweaks %}

{% block profile_subtitle %}Account details{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-header">Email address</div>
	<div class="message-body content">
		<p>Sorry, email change is currently under maintenance.</p>
		<p>If you need to change it right now, check out <a href="/help/">the help page</a> on how to get in contact, we may be able to do it manually.</p>
	</div>
</div>

{% endblock %}

dpusers/templates/users/password_change.html
{% extends "users/base.html" %}

{% load widget_tweaks %}

{% block profile_subtitle %}Change password{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-body">
		<form method="post" class="disable-button-on-submit">
			{% if form.non_field_errors %}
			<div class="notification is-danger">{{ form.non_field_errors }}</div>
			{% endif %}
			{% for field in form %}
			<div class="field">
				<div class="control">
					{% render_field field class+="input" placeholder=field.label %}
				</div>
				{% if field.errors %}<div class="help is-danger">{{ field.errors }}</div>{% endif %}
			</div>{# /.field #}
			{% endfor %}

			<div class="field">
				<div class="control">
					<input type="submit" value="Change password" class="button is-danger">
				</div>
			</div>{# /.field #}
			{% csrf_token %}
		</form>
	</div>
</div>

{% endblock %}

dpusers/templates/users/password_change_done.html
{% extends "users/base.html" %}

{% load widget_tweaks %}

{% block profile_subtitle %}Change password{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-header">Password</div>
	<div class="message-body">
		<p>Password changed!</p>
	</div>
</div>

{% endblock %}

dpusers/templates/users/usernames.html
{% extends "users/base.html" %}

{% load static %}

{% block profile_subtitle %}Usernames{% endblock %}

{% block extrahead %}{{ block.super }}
<meta name="max-users" content="{{ max_users }}">
{% endblock %}

{% block extrascripts %}<script src="{% static "js/manage_usernames.min.js" %}" type="module"></script>{% endblock %}

{% block profile_main %}

<div class="message">
	<div class="message-body">
		<div class="content">
			<p>Here you can reserve names for use on <a href="/communities/">the community servers</a> and any other Drawpile server that uses drawpile.net accounts.</p>
			<p>Note that alternative usernames are not hidden! If you need alts for privacy, you must register a separate account with another email address.</p>
			{% if mod_available %}
				<p>Setting the Mod flag activates moderator privileges for that username. You have the following moderator role{{ mod_status|length|pluralize }}:</p>
				<ul>
					{% for m in mod_status %}
					<li>{{ m }}</li>
					{% endfor %}
				</ul>
			{% endif %}
		</div>
		<div id="username-list" data-permissions="{{ permissions }}"></div>
	</div>
</div>

{% endblock %}