dpauth/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from .viewsets import UsernameViewSet

router = routers.DefaultRouter()

router.register(r'', UsernameViewSet, basename='username')

urlpatterns = [
    url(r'^', include(router.urls)),
    ]

dpauth/urls.py
from django.urls import path, re_path
from . import views

app_name = "auth"
urlpatterns = [
    path("", views.AuthUsernamesView.as_view(), name="usernames"),
    re_path(r"^finish/(?P<name>.+)/$", views.AuthFinishView.as_view(), name="finish"),
    path("login/", views.AuthLoginView.as_view(), name="login"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
    path("ban-analyzer/", views.BanAnalyzerView.as_view(), name="ban-analyzer"),
    path(
        "monitor-manager/", views.MonitorManagerView.as_view(), name="monitor-manager"
    ),
    path(
        "monitor-manager/restart",
        views.MonitorManagerRestartView.as_view(),
        name="monitor-manager-restart",
    ),
]

dpusers/urls.py
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from django.urls import reverse_lazy
from django.urls import path, re_path

from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('tos/', RedirectView.as_view(url='/tos/', permanent=False)),
]

if settings.DRAWPILE_READONLY_SITE:
    urlpatterns += [
        re_path(r'.*', RedirectView.as_view(url='/readonly/', permanent=False)),
    ]
else:
    urlpatterns += [
        path('signup/', views.SignupView.as_view(), name='signup'),
        path('finish-signup/', views.FinishSignupView.as_view(), name='finish-signup'),

        path('profile/', views.AccountView.as_view(), name='profile-account'),
        path('profile/email_change/', views.EmailChangeView.as_view(), name='profile-emailchange'),
        path('profile/email_change/confirm/', views.ConfirmEmailChangeView.as_view(), name='profile-emailchange-confirm'),
        path('profile/usernames/', views.UsernameView.as_view(), name='profile-usernames'),

        path('delete/', views.DeleteAccountView.as_view(), name='delete-account'),

        # Views provided by Django:
        path('login/', auth_views.LoginView.as_view(), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),

        path(
            'profile/password_change/',
            auth_views.PasswordChangeView.as_view(
                template_name='users/password_change.html',
                success_url=reverse_lazy('users:password_change_done'),
                extra_context={'profile_page': 'password_change'}
            ),
            name='password_change'
        ),
        path(
            'profile/password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(
                template_name='users/password_change_done.html',
                extra_context={'profile_page': 'password_change'}
                ),
            name='password_change_done'
        ),
        path(
            'password_reset/',
            views.ResetPasswordView.as_view(),
            name='password_reset'
        ),
        path(
            'password_reset/done/',
            auth_views.PasswordResetDoneView.as_view(
                template_name='registration/reset_password_done.html'
            ),
            name='password_reset_done'
        ),
        path(
            'reset/<uidb64>/<token>/',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='registration/reset_password_confirm.html',
                success_url=reverse_lazy('users:password_reset_complete')
            ),
            name='password_reset_confirm'
        ),
        path(
            'reset/done/',
            auth_views.PasswordResetCompleteView.as_view(
                template_name='registration/reset_password_complete.html'
            ),
            name='password_reset_complete'
        ),
    ]

drawpile/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.conf import settings

from templatepages.views import DocumentationDetailView, TemplatePageView


class DonationRedirectView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        try:
            lang = self.request.GET["lang"]
            if lang and lang.startswith("de_"):
                return self.url + "de/"
        except:
            pass
        return self.url


urlpatterns = [
    path('_admin/', admin.site.urls),
    path('api/', include('drawpile.api_urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('dpusers.urls')),
    path('auth/', include('dpauth.urls')),
    path('communities/', include('communities.urls')),
    path('invites/', include('invites.urls')),
    path('ban/', RedirectView.as_view(
        url='/communities/drawpile.net/ban/', permanent=True)),
    path('readonly/', TemplateView.as_view(template_name='readonly.html')
        if settings.DRAWPILE_READONLY_SITE
        else RedirectView.as_view(url='/', permanent=False)),
    path('discord/', RedirectView.as_view(url='https://discord.gg/VHRDh2fKnc', permanent=True)),
    path('fedi/', RedirectView.as_view(url='https://floss.social/@drawpile', permanent=True)),
    path('matrix/', RedirectView.as_view(url='https://matrix.to/#/#drawpile:matrix.org', permanent=True)),
    path('localhosthelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/common/hosting#builtin-server', permanent=True)),
    path('pubrules/', RedirectView.as_view(url='/communities/drawpile.net/ccg/', permanent=True)),
    path('sharedarraybufferhelp/', RedirectView.as_view(url='https://docs.drawpile.net/help/tech/browser#sharedarraybuffer-issues', permanent=True)),
    path('lgm/', TemplateView.as_view(template_name='lgm.html')),
    path('namecheckbot/', TemplateView.as_view(template_name='namecheckbot.html')),
    path('donate/', DonationRedirectView.as_view(url="https://donate.drawpile.org/", permanent=True)),
    path('', TemplateView.as_view(template_name='pages/index.html')),
]

if hasattr(settings, "DRAWPILE_IMPRESSUM"):
    urlpatterns += path('impressum/', TemplateView.as_view(template_name='impressum.html')),

if hasattr(settings, "DRAWPILE_PRIVACY_POLICY"):
    urlpatterns += path('privacy/', TemplateView.as_view(template_name='privacy.html')),

if hasattr(settings, "DRAWPILE_TOS"):
    urlpatterns += path('tos/', TemplateView.as_view(template_name='tos.html')),

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

urlpatterns += [
    path('docs/<slug:slug>/', DocumentationDetailView.as_view(), name='documentation-detail'),
    re_path(r'^(?P<path>.*)/$', TemplatePageView.as_view()),
]

news/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.NewsListView.as_view(), name="list"),
    path('feed.atom', views.NewsFeed(), name="atom-feed"),
    path('release-2.3.0-beta.1/', RedirectView.as_view(url="/news/release-2.3.0-beta.2/", permanent=True)),
    path('<slug>/', views.NewsDetailView.as_view(), name='detail'),
]

dpauth/forms.py
from django import forms
from .models import Username


class AuthUsernamesForm(forms.Form):
    username = forms.CharField()

    def __init__(self, *args, **kwargs):
        self.__user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

    def clean_username(self):
        name = self.cleaned_data["username"]
        if self.__user.drawpilename_set.filter(name=name).exists():
            return name
        else:
            raise forms.ValidationError(f'Username "{name}" does not exist.')


class MonitorRestartForm(forms.Form):
    pass

dpauth/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import FormView, TemplateView
import logging
import subprocess
from .forms import AuthUsernamesForm, MonitorRestartForm
from .models import Username

logger = logging.getLogger(__name__)


class AuthLoginView(LoginView):
    redirect_authenticated_user = True
    next_page = "auth:usernames"
    redirect_field_name = None
    template_name = "auth_login.html"

    def get_success_url(self):
        return reverse("auth:usernames")


class AuthLogoutView(LogoutView):
    redirect_authenticated_user = True
    next_page = "auth:login"
    redirect_field_name = None

    def get_success_url(self):
        return reverse("auth:login")


class AuthUsernamesView(LoginRequiredMixin, FormView):
    form_class = AuthUsernamesForm
    login_url = "auth:login"
    redirect_field_name = None
    template_name = "auth_usernames.html"

    def get(self, request, *args, **kwargs):
        name = request.GET.get("name")
        if name and request.user.drawpilename_set.filter(name=name).exists():
            return redirect("auth:finish", name)
        else:
            return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update(
            {
                "usernames": list(self.request.user.drawpilename_set.all()),
            }
        )
        return ctx

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        name = form.cleaned_data["username"]
        self.success_url = reverse("auth:finish", args=[name])
        return super().form_valid(form)


class AuthFinishView(LoginRequiredMixin, TemplateView):
    template_name = "auth_finish.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update(
            {
                "frame_ancestors": settings.DRAWPILE_AUTH_FRAME_ANCESTORS,
            }
        )
        return ctx


class BanAnalyzerView(PermissionRequiredMixin, TemplateView):
    template_name = "ban_analyzer.html"
    permission_required = "dpauth.change_ban"


class MonitorManagerView(PermissionRequiredMixin, TemplateView):
    template_name = "monitor_manager.html"
    permission_required = "dpauth.view_monitorwordlist"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = self.request.user
        command = settings.DRAWPILE_MONITOR_STATUS_COMMAND
        if not command:
            raise ValueError("DRAWPILE_MONITOR_STATUS_COMMAND not configured")
        logger.info(
            "Checking drawpile-monitor status at the behest of %s (%d): %s",
            user.username,
            user.id,
            command,
        )
        process = subprocess.run(
            command,
            timeout=5,
            encoding="UTF-8",
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        ctx.update(
            {
                "status_returncode": process.returncode,
                "status_stdout": process.stdout,
                "can_restart": user.has_perm("dpauth.change_monitorwordlist",)
            }
        )
        return ctx


class MonitorManagerRestartView(PermissionRequiredMixin, FormView):
    permission_required = "dpauth.change_monitorwordlist"
    form_class = MonitorRestartForm

    def get_success_url(self):
        return reverse("auth:monitor-manager")

    def form_valid(self, form):
        user = self.request.user
        command = settings.DRAWPILE_MONITOR_RELOAD_COMMAND
        if not command:
            raise ValueError("DRAWPILE_MONITOR_RELOAD_COMMAND not configured")
        logger.info(
            "Restarting drawpile-monitor at the behest of %s (%d): %s",
            user.username,
            user.id,
            command,
        )
        process = subprocess.run(
            command,
            timeout=5,
            encoding="UTF-8",
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        logger.info(
            "Restarted drawpile-monitor result %d: %s",
            process.returncode,
            process.stdout,
        )
        if process.returncode == 0:
            messages.success(self.request, "Restarted drawpile-monitor successfully.")
        else:
            messages.error(
                self.request,
                f"Restart exited with {process.returncode}, check logs for details.",
            )
        return super().form_valid(form)

dpauth/templates/admin_bans_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls %}
{% block object-tools %}
    {{ block.super }}
    <p>⚠️ <em>Make sure to read <strong><a href="/docs/extbans/" target="_blank">the instructions</a></strong> first!</em></p>
    <p>🔧 Use the <strong><a href="/auth/ban-analyzer/" target="_blank">community ban analyzer tool</a></strong> to extract the required information from the session logs.</p>
    <hr>
{% endblock %}

dpauth/templates/admin_bans_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls %}
{% block object-tools %}
    {{ block.super }}
    <p>⚠️ <em>Make sure to read <strong><a href="/docs/extbans/" target="_blank">the instructions</a></strong> first!</em></p>
    <p>🔧 Use the <strong><a href="/auth/ban-analyzer/" target="_blank">community ban analyzer tool</a></strong> to extract the required information from the session logs.</p>
{% endblock %}

dpauth/templates/admin_monitorwordlist_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls %}
{% block object-tools %}
    {{ block.super }}
    <p>🔧 Use the <strong><a href="/auth/monitor-manager/" target="_blank">monitor manager</a></strong> to restart the name check bot after changing something here.</p>
{% endblock %}

dpauth/templates/auth_finish.html
{% extends "framebase.html" %}

{% load static %}

{% block title %}Logging in - {{ block.super }}{% endblock %}

{% block extrascripts %}<script src="{% static "js/auth_finish.min.js" %}"></script>{% endblock %}

{% block main %}
<div id="auth" data-username="{{ name }}" data-frameancestors="{{ frame_ancestors }}" class="content is-large has-text-centered">
	<p id="auth-message">
		<span class="fa fa-spinner fa-pulse"></span>
		Logging in as {{ name }}…
	</p>
	<noscript>
		<p>You need to enable scripts for drawpile.net for this to work.</p>
	</noscript>
</div>
{% endblock %}

dpauth/templates/auth_login.html
{% extends "framebase.html" %}

{% load widget_tweaks %}

{% block title %}Sign in - {{ block.super }}{% endblock %}

{% block main %}
<form method="POST" action="{% url 'auth:login' %}" class="disable-button-on-submit">
	{% if form.non_field_errors %}
	<div class="notification is-danger">{{ form.non_field_errors }}</div>
	{% endif %}

	<div class="field">
		<div class="control has-icons-left">
			{% render_field form.username class+="input is-large" placeholder="Username or email" %}
			<span class="icon is-small is-left"> <i class="fa fa-at"></i> </span>
		</div>
		{% if form.errors.username %}<p class="help is-danger">{{ form.errors.username }}</p>{% endif %}
	</div>

	<div class="field">
		<div class="control has-icons-left">
			{% render_field form.password class+="input is-large" placeholder="Password" %}
			<span class="icon is-small is-left"> <i class="fa fa-lock"></i> </span>
		</div>
		{% if form.errors.password %}<p class="help is-danger">{{ form.errors.password }}</p>{% endif %}
	</div>

	<div class="field">
		<p>If you do not already have a drawpile.net account, you can <a href="{% url 'users:signup' %}" target="_blank">sign up here</a>.</p>
		<p>If you have forgotten your password, you can <a href="{% url 'users:password_reset' %}" target="_blank">reset it here</a>.</p>
		<p>Accounts are deleted after one year of inactivity.</p>
	</div>

	<div class="field">
		<button type="submit" class="button is-fullwidth is-link is-large">
			<span class="fa fa-sign-in-alt"></span>&nbsp;Sign In
		</button>
	</div>
	<hr>
	<div class="field">
		<a class="button is-fullwidth" href=".">
			<span class="fa fa-sync-alt"></span>&nbsp;Refresh
		</a>
	</div>
	{% csrf_token %}
</form>
{% endblock %}

dpauth/templates/auth_usernames.html
{% extends "framebase.html" %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Choose Username - {{ block.super }}{% endblock %}

{% block extrahead %}<link rel="stylesheet" href="{% static "css/auth_usernames.css" %}">{% endblock %}

{% block main %}
{% if form.non_field_errors %}
<div class="notification is-danger">{{ form.non_field_errors }}</div>
{% endif %}
{% if form.errors.username %}
<div class="notification is-danger">{{ form.errors.username }}</div>
{% endif %}
<div class="message">
	<div class="message-body">
		<div class="content">
			<p>Choose the username you want to log in with. You can change your reserved usernames <a href="{% url 'users:profile-usernames' %}" target="_blank">in your account settings</a>.</p>
		</div>
		<form id="auth-usernames-form" method="POST" action="{% url 'auth:usernames' %}" class="tile is-ancestor is-vertical disable-button-on-submit">
			{% for username in usernames %}
				<button type="submit" class="tile is-child box auth-username" name="username" value="{{ username.name }}">
					<div class="media">
						<div class="media-left">
							<figure class="image is-64x64">
								{% if username.avatar %}
									<img src="{{ username.avatar.url }}" alt="Avatar for {{ username.name }}">
								{% else %}
									<span class="avatar-placeholder"></span>
								{% endif %}
							</figure>
						</div>
						<div class="media-content">
							<div class="content is-large">
								<p>{{ username.name }}</p>
							</div>
						</div>
					</div>
				</button>
			{% endfor %}
			{% csrf_token %}
		</form>
	</div>
</div>
<hr>
<div class="field is-grouped">
	<div class="control is-expanded">
		<a class="button is-fullwidth" href=".">
			<span class="fa fa-sync-alt"></span>&nbsp;Refresh
		</a>
	</div>
	<form method="POST" action="{% url 'auth:logout' %}" class="control disable-button-on-submit is-expanded">
		<button type="submit" class="button is-fullwidth is-danger">
			<span class="fa fa-sign-out-alt"></span>&nbsp;Log Out
		</button>
		{% csrf_token %}
	</form>
</div>
{% endblock %}

dpauth/templates/ban_analyzer.html
{% extends "base.html" %}

{% load static %}

{% block title %}Community Ban Analyzer - {{ block.super }}{% endblock %}

{% block extrascripts %}<script src="{% static "js/ban_analyzer.min.js" %}"></script>{% endblock %}

{% block main %}
<section class="section">
    <div class="container">
		<h1 class="title">Community Ban Analyzer</h1>
		<div class="content">
			<p>To use this, join the offending session and go into Session → Event Log. Filter for <code>"address"</code>. Alternatively, look in the server logs themselves.</p>
			<p>Copy the results into the text field below and the table will take it apart. It will ignore extra data, so just copy a bunch of stuff and it will figure it out.</p>
			<p><strong>OS</strong> tells you what operating system the person is on, Emscripten refers to the browser version. You don't need to copy it anywhere, it's just informative.</p>
			<p>Include the <strong>Username</strong> into the "Description" field, along with the reason for the ban.</p>
			<p><strong>IP Address</strong> goes into the "Start of IP Range" field. Leave the "End of IP Range (inclusive)" field empty.</p>
			<p><strong>System Identifier</strong> and <strong>User ID</strong> go into those respective fields.</p>
			<p>Make sure to <a href="/docs/extbans/" target="_blank">read the instructions</a> on bans. Also, remember to paste the data into the <code>#community-moderators</code> chat on Discord, so that others can check what you did, it helps avoid mistakes.</p>
		</div>
		<div class="field">
			<textarea id="ban-analyzer-input" class="textarea" placeholder="Paste logs here" rows="5"></textarea>
		</div>
		<div class="table-container">
			<table class="table is-bordered is-hoverable is-fullwidth is-striped">
				<thead>
					<tr>
						<th>OS</th>
						<th>Username</th>
						<th>IP Address</th>
						<th>System Identifer</th>
						<th>User ID</th>
					</tr>
				</thead>
				<tbody id="ban-analyzer-results">
					<tr><td colspan="5">Loading…</td></tr>
				</tbody>
			</table>
		</div>
    </div>
</section>
{% endblock %}

dpauth/templates/monitor_manager.html
{% extends "base.html" %}

{% load static %}

{% block title %}Monitor Management - {{ block.super }}{% endblock %}

{% block main %}
<section class="section">
    <div class="container">
		{% if messages %}
		{% for message in messages %}
		<div class="notification{% if message.tags %} is-light is-{% if "error" in message.tags %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}">
			{{ message }}
		</div>
		{% endfor %}
		{% endif %}
		<h1 class="title">Monitor Management</h1>
		<div class="content">
			<p>
				{% if status_returncode == 0 %}
				Name check bot status:
				{% else %}
				Name check bot status check exited with {{ status_returncode }}:
				{% endif %}
			</p>
			<pre>{{ status_stdout }}</pre>
		</div>
		{% if can_restart %}
		<form method="POST" action="{% url 'auth:monitor-manager-restart' %}" class="disable-button-on-submit">
			<button class="button is-link" type="submit">
				Restart Monitor
			</button>
			{% csrf_token %}
		</form>
		{% endif %}
    </div>
</section>
{% endblock %}